// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class Almacen
{
    /// <summary>
    /// Almacén ID
    /// </summary>
    [Key]
    public int IdAlmacen { get; set; }

    /// <summary>
    /// Código
    /// </summary>
    [Required]
    [StringLength(20)]
    public string Codigo { get; set; }

    /// <summary>
    /// Descripción
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Descripcion { get; set; }

    /// <summary>
    /// Local ID
    /// </summary>
    public int? IdLocal { get; set; }

    /// <summary>
    /// Tipo ID
    /// </summary>
    public int IdTipoAlmacen { get; set; }

    /// <summary>
    /// Dirección ID
    /// </summary>
    public int? IdDireccion { get; set; }

    /// <summary>
    /// Responsable Id
    /// </summary>
    public int? IdResponsable { get; set; }

    /// <summary>
    /// Area Metros Cuadrados
    /// </summary>
    [Column(TypeName = "decimal(19, 6)")]
    public decimal Superficie { get; set; }

    /// <summary>
    /// Capacidad Kg
    /// </summary>
    [Column(TypeName = "decimal(19, 6)")]
    public decimal Capacidad { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [InverseProperty("AlmacenDefault")]
    public virtual ICollection<Articulo> Articulo { get; set; } = new List<Articulo>();

    [ForeignKey("IdDireccion")]
    [InverseProperty("Almacen")]
    public virtual Direccion IdDireccionNavigation { get; set; }

    [ForeignKey("IdResponsable")]
    [InverseProperty("Almacen")]
    public virtual Socio IdResponsableNavigation { get; set; }

    [ForeignKey("IdTipoAlmacen")]
    [InverseProperty("Almacen")]
    public virtual TipoAlmacen IdTipoAlmacenNavigation { get; set; }
}