// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class Articulo
{
    /// <summary>
    /// Artículo ID
    /// </summary>
    [Key]
    public int IdArticulo { get; set; }

    /// <summary>
    /// Código Artículo
    /// </summary>
    [Required]
    [StringLength(10)]
    public string CodigoArticulo { get; set; }

    /// <summary>
    /// Descripción
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Descripcion { get; set; }

    /// <summary>
    /// Sub Grupo Artículo ID
    /// </summary>
    public int IdSubGrupoArticulo { get; set; }

    /// <summary>
    /// Unidad Inventario ID
    /// </summary>
    public int? IdUnidadInventario { get; set; }

    /// <summary>
    /// Unidad Compra ID
    /// </summary>
    public int? IdUnidadCompra { get; set; }

    /// <summary>
    /// Unidad Venta ID
    /// </summary>
    public int? IdUnidadVenta { get; set; }

    /// <summary>
    /// Tipo Artículo ID
    /// </summary>
    public int? IdTipoArticulo { get; set; }

    /// <summary>
    /// Tipo Detracción Sunat ID
    /// </summary>
    public int? IdTipoDetraccion { get; set; }

    /// <summary>
    /// Tipo Valorización ID
    /// </summary>
    public int? IdTipoValorizacion { get; set; }

    /// <summary>
    /// Tipo Existencia Sunat ID
    /// </summary>
    public int? IdTipoExistencia { get; set; }

    /// <summary>
    /// Stock Mínimo
    /// </summary>
    [Column(TypeName = "decimal(19, 6)")]
    public decimal StockMinimo { get; set; }

    /// <summary>
    /// Stock Máximo
    /// </summary>
    [Column(TypeName = "decimal(19, 6)")]
    public decimal StockMaximo { get; set; }

    /// <summary>
    /// Stock de Seguridad
    /// </summary>
    [Column(TypeName = "decimal(19, 6)")]
    public decimal StockSeguridad { get; set; }

    /// <summary>
    /// Observaciones
    /// </summary>
    [StringLength(1000)]
    public string Observaciones { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [InverseProperty("IdArticuloNavigation")]
    public virtual ICollection<ArticuloImagen> ArticuloImagen { get; set; } = new List<ArticuloImagen>();

    [ForeignKey("IdSubGrupoArticulo")]
    [InverseProperty("Articulo")]
    public virtual SubGrupoArticulo IdSubGrupoArticuloNavigation { get; set; }

    [ForeignKey("IdTipoArticulo")]
    [InverseProperty("Articulo")]
    public virtual TipoArticulo IdTipoArticuloNavigation { get; set; }

    [ForeignKey("IdTipoDetraccion")]
    [InverseProperty("Articulo")]
    public virtual SunatTipoDetraccion IdTipoDetraccionNavigation { get; set; }

    [ForeignKey("IdTipoExistencia")]
    [InverseProperty("Articulo")]
    public virtual SunatTipoExistencia IdTipoExistenciaNavigation { get; set; }

    [ForeignKey("IdTipoValorizacion")]
    [InverseProperty("Articulo")]
    public virtual TipoValorizacion IdTipoValorizacionNavigation { get; set; }

    [ForeignKey("IdUnidadCompra")]
    [InverseProperty("ArticuloIdUnidadCompraNavigation")]
    public virtual UnidadMedida IdUnidadCompraNavigation { get; set; }

    [ForeignKey("IdUnidadInventario")]
    [InverseProperty("ArticuloIdUnidadInventarioNavigation")]
    public virtual UnidadMedida IdUnidadInventarioNavigation { get; set; }

    [ForeignKey("IdUnidadVenta")]
    [InverseProperty("ArticuloIdUnidadVentaNavigation")]
    public virtual UnidadMedida IdUnidadVentaNavigation { get; set; }

    [InverseProperty("IdArticuloNavigation")]
    public virtual ICollection<SocioPrecioArticulo> SocioPrecioArticulo { get; set; } = new List<SocioPrecioArticulo>();

    [InverseProperty("IdArticuloNavigation")]
    public virtual ICollection<TicketPesajes> TicketPesajes { get; set; } = new List<TicketPesajes>();
}