// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class ArticuloImagen
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    public int IdArticuloImagen { get; set; }

    /// <summary>
    /// Artículo ID
    /// </summary>
    public int IdArticulo { get; set; }

    /// <summary>
    /// Imagen ID
    /// </summary>
    public int? IdImagen { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [ForeignKey("IdArticulo")]
    [InverseProperty("ArticuloImagen")]
    public virtual Articulo IdArticuloNavigation { get; set; }

    [ForeignKey("IdImagen")]
    [InverseProperty("ArticuloImagen")]
    public virtual Imagenes IdImagenNavigation { get; set; }
}