// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class CentroCosto
{
    /// <summary>
    /// Centro Costo ID
    /// </summary>
    [Key]
    public int IdCentroCosto { get; set; }

    /// <summary>
    /// Nivel Centro Costo ID
    /// </summary>
    public int IdNivelCentroCosto { get; set; }

    /// <summary>
    /// Código
    /// </summary>
    [Required]
    [StringLength(16)]
    [Unicode(false)]
    public string CodigoCentroCosto { get; set; }

    /// <summary>
    /// Descripción
    /// </summary>
    [Required]
    [StringLength(60)]
    public string Descripcion { get; set; }

    /// <summary>
    /// Centro Costo Padre
    /// </summary>
    public int? IdCentroCostoPadre { get; set; }

    /// <summary>
    /// ¿Es nivel específico?
    /// </summary>
    public bool EsNivelEspecifico { get; set; }

    /// <summary>
    /// ¿Es Agricola?
    /// </summary>
    public bool EsAgricola { get; set; }

    /// <summary>
    /// Hectáreas
    /// </summary>
    [Column(TypeName = "decimal(19, 3)")]
    public decimal Hectareas { get; set; }

    /// <summary>
    /// Distancia entre hileras metros
    /// </summary>
    [Column(TypeName = "decimal(9, 2)")]
    public decimal DistanciaEntreHilerasMetros { get; set; }

    /// <summary>
    /// Número de Lote
    /// </summary>
    [Required]
    [StringLength(10)]
    public string NumeroLote { get; set; }

    /// <summary>
    /// Unidad de Gasto ID
    /// </summary>
    public int? IdUnidadGasto { get; set; }

    /// <summary>
    /// Sistema Conducción ID
    /// </summary>
    public int? IdSistemaConduccion { get; set; }

    /// <summary>
    /// Cultivo ID
    /// </summary>
    public int? IdCultivo { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [ForeignKey("IdCentroCostoPadre")]
    [InverseProperty("InverseIdCentroCostoPadreNavigation")]
    public virtual CentroCosto IdCentroCostoPadreNavigation { get; set; }

    [ForeignKey("IdCultivo")]
    [InverseProperty("CentroCosto")]
    public virtual Cultivo IdCultivoNavigation { get; set; }

    [ForeignKey("IdNivelCentroCosto")]
    [InverseProperty("CentroCosto")]
    public virtual NivelCentroCosto IdNivelCentroCostoNavigation { get; set; }

    [ForeignKey("IdSistemaConduccion")]
    [InverseProperty("CentroCosto")]
    public virtual SistemaConduccion IdSistemaConduccionNavigation { get; set; }

    [ForeignKey("IdUnidadGasto")]
    [InverseProperty("CentroCosto")]
    public virtual UnidadGasto IdUnidadGastoNavigation { get; set; }

    [InverseProperty("IdCentroCostoPadreNavigation")]
    public virtual ICollection<CentroCosto> InverseIdCentroCostoPadreNavigation { get; set; } = new List<CentroCosto>();
}