// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class Departamento
{
    /// <summary>
    /// Departamento ID
    /// </summary>
    [Key]
    public int IdDepartamento { get; set; }

    /// <summary>
    /// Código
    /// </summary>
    [Required]
    [StringLength(4)]
    public string CodigoDepartamento { get; set; }

    /// <summary>
    /// Nombre
    /// </summary>
    [Required]
    [StringLength(60)]
    public string DepartamentoName { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [InverseProperty("IdDepartamentoNavigation")]
    public virtual ICollection<Provincia> Provincia { get; set; } = new List<Provincia>();
}