// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class Distrito
{
    /// <summary>
    /// Distrito ID
    /// </summary>
    [Key]
    public int IdDistrito { get; set; }

    /// <summary>
    /// Código
    /// </summary>
    [Required]
    [StringLength(6)]
    public string CodigoDistrito { get; set; }

    /// <summary>
    /// Distrito
    /// </summary>
    [Required]
    [Column("Distrito")]
    [StringLength(100)]
    public string Distrito1 { get; set; }

    /// <summary>
    /// Provincia ID
    /// </summary>
    public int IdProvincia { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [InverseProperty("IdDistritoNavigation")]
    public virtual ICollection<Direccion_> Direccion_ { get; set; } = new List<Direccion_>();

    [ForeignKey("IdProvincia")]
    [InverseProperty("Distrito")]
    public virtual Provincia IdProvinciaNavigation { get; set; }
}