// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class Imagenes
{
    /// <summary>
    /// Imagen ID
    /// </summary>
    [Key]
    public int IdImagen { get; set; }

    /// <summary>
    /// Nombre
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Nombre { get; set; }

    /// <summary>
    /// Ruta
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Ruta { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    /// <summary>
    /// Imagen
    /// </summary>
    [Required]
    public byte[] Imagen { get; set; }

    [InverseProperty("IdImagenNavigation")]
    public virtual ICollection<ArticuloImagen> ArticuloImagen { get; set; } = new List<ArticuloImagen>();

    [InverseProperty("IdImagenNavigation")]
    public virtual ICollection<Empresa> Empresa { get; set; } = new List<Empresa>();
}