// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jodami.Entity;

public partial class Provincia
{
    /// <summary>
    /// Provincia ID
    /// </summary>
    public int IdProvincia { get; set; }

    /// <summary>
    /// Código
    /// </summary>
    public string CodigoProvincia { get; set; }

    /// <summary>
    /// Provincia
    /// </summary>
    public string Provincia1 { get; set; }

    /// <summary>
    /// Departamento ID
    /// </summary>
    public int IdDepartamento { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    public DateTime FechaRegistro { get; set; }

    public virtual ICollection<Distrito> Distrito { get; set; } = new List<Distrito>();

    public virtual Departamento IdDepartamentoNavigation { get; set; }
}