// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class Provincia
{
    /// <summary>
    /// Provincia ID
    /// </summary>
    [Key]
    public int IdProvincia { get; set; }

    /// <summary>
    /// Código
    /// </summary>
    [Required]
    [StringLength(4)]
    public string CodigoProvincia { get; set; }

    /// <summary>
    /// Nombre
    /// </summary>
    [Required]
    [StringLength(60)]
    public string ProvinciaName { get; set; }

    /// <summary>
    /// Departamento ID
    /// </summary>
    public int IdDepartamento { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [InverseProperty("IdProvinciaNavigation")]
    public virtual ICollection<Distrito> Distrito { get; set; } = new List<Distrito>();

    [ForeignKey("IdDepartamento")]
    [InverseProperty("Provincia")]
    public virtual Departamento IdDepartamentoNavigation { get; set; }
}