// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class RolMenu
{
    /// <summary>
    /// Rol Menú ID
    /// </summary>
    [Key]
    public int IdRolMenu { get; set; }

    /// <summary>
    /// Rol ID
    /// </summary>
    public int? IdRol { get; set; }

    /// <summary>
    /// Menú ID
    /// </summary>
    public int? IdMenu { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool? EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? FechaRegistro { get; set; }

    [ForeignKey("IdMenu")]
    [InverseProperty("RolMenu")]
    public virtual Menu IdMenuNavigation { get; set; }

    [ForeignKey("IdRol")]
    [InverseProperty("RolMenu")]
    public virtual Rol IdRolNavigation { get; set; }
}