// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

[Table("SocioDireccion ")]
public partial class SocioDireccion_
{
    /// <summary>
    /// Dirección ID
    /// </summary>
    [Key]
    public int IdDireccion { get; set; }

    /// <summary>
    /// Socio ID
    /// </summary>
    public int SocioId { get; set; }

    /// <summary>
    /// Dirección Asociada
    /// </summary>
    public int DireccionId { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [ForeignKey("IdDireccion")]
    [InverseProperty("SocioDireccion_")]
    public virtual Direccion_ IdDireccionNavigation { get; set; }

    [ForeignKey("SocioId")]
    [InverseProperty("SocioDireccion_")]
    public virtual Socio Socio { get; set; }
}