// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class SocioDireccion
{
    /// <summary>
    /// Dirección Socio ID
    /// </summary>
    [Key]
    public int IdSocioDireccion { get; set; }

    /// <summary>
    /// Socio ID
    /// </summary>
    public int? IdSocio { get; set; }

    /// <summary>
    /// Dirección ID
    /// </summary>
    public int? IdDireccion { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [ForeignKey("IdDireccion")]
    [InverseProperty("SocioDireccion")]
    public virtual Direccion IdDireccionNavigation { get; set; }

    [ForeignKey("IdSocio")]
    [InverseProperty("SocioDireccion")]
    public virtual Socio IdSocioNavigation { get; set; }
}