// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class SocioContacto
{
    /// <summary>
    /// Contacto ID
    /// </summary>
    [Key]
    public int IdContacto { get; set; }

    /// <summary>
    /// Socio ID
    /// </summary>
    public int IdSocio { get; set; }

    /// <summary>
    /// Nombres
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Nombre { get; set; }

    /// <summary>
    /// Cargo ID
    /// </summary>
    public int? IdCargo { get; set; }

    /// <summary>
    /// Teléfono
    /// </summary>
    [StringLength(20)]
    public string Telefono { get; set; }

    /// <summary>
    /// Celular
    /// </summary>
    [StringLength(20)]
    public string Celular { get; set; }

    /// <summary>
    /// ¿ Celular para Whats App ?
    /// </summary>
    public bool IsCelularWhatsApp { get; set; }

    /// <summary>
    /// Email
    /// </summary>
    [StringLength(100)]
    public string Email { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [ForeignKey("IdCargo")]
    [InverseProperty("SocioContacto")]
    public virtual Cargo IdCargoNavigation { get; set; }

    [ForeignKey("IdSocio")]
    [InverseProperty("SocioContacto")]
    public virtual Socio IdSocioNavigation { get; set; }
}