// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class SocioFormaPago
{
    /// <summary>
    /// Forma Pago ID
    /// </summary>
    [Key]
    public int IdFormaPago { get; set; }

    /// <summary>
    /// Socio ID
    /// </summary>
    public int IdSocio { get; set; }

    /// <summary>
    /// Tipo Forma Pago ID
    /// </summary>
    public int IdTipoFormaPago { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [ForeignKey("IdSocio")]
    [InverseProperty("SocioFormaPago")]
    public virtual Socio IdSocioNavigation { get; set; }

    [ForeignKey("IdTipoFormaPago")]
    [InverseProperty("SocioFormaPago")]
    public virtual TipoFormaPago IdTipoFormaPagoNavigation { get; set; }
}