// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class SocioPrecioArticulo
{
    /// <summary>
    /// Precio Artículo ID
    /// </summary>
    [Key]
    public int IdPrecioArticulo { get; set; }

    /// <summary>
    /// Socio ID
    /// </summary>
    public int IdSocio { get; set; }

    /// <summary>
    /// Artículo ID
    /// </summary>
    public int IdArticulo { get; set; }

    /// <summary>
    /// Moneda ID
    /// </summary>
    public int IdMoneda { get; set; }

    /// <summary>
    /// Precio Unitario
    /// </summary>
    [Column(TypeName = "decimal(19, 6)")]
    public decimal PrecioUnitario { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [ForeignKey("IdArticulo")]
    [InverseProperty("SocioPrecioArticulo")]
    public virtual Articulo IdArticuloNavigation { get; set; }

    [ForeignKey("IdMoneda")]
    [InverseProperty("SocioPrecioArticulo")]
    public virtual Moneda IdMonedaNavigation { get; set; }

    [ForeignKey("IdSocio")]
    [InverseProperty("SocioPrecioArticulo")]
    public virtual Socio IdSocioNavigation { get; set; }
}