// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class SubGrupoArticulo
{
    /// <summary>
    /// Sub Grupo ID
    /// </summary>
    [Key]
    public int IdSubGrupoArticulo { get; set; }

    /// <summary>
    /// Grupo ID
    /// </summary>
    public int IdGrupoArticulo { get; set; }

    /// <summary>
    /// Código
    /// </summary>
    [Required]
    [StringLength(4)]
    public string Codigo { get; set; }

    /// <summary>
    /// Descripción
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Descripcion { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool Activo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [InverseProperty("IdSubGrupoArticuloNavigation")]
    public virtual ICollection<Articulo> Articulo { get; set; } = new List<Articulo>();

    [ForeignKey("IdGrupoArticulo")]
    [InverseProperty("SubGrupoArticulo")]
    public virtual GrupoArticulo IdGrupoArticuloNavigation { get; set; }
}