// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class Ticket
{
    /// <summary>
    /// Ticket ID
    /// </summary>
    [Key]
    public int IdTicket { get; set; }

    /// <summary>
    /// NúmeroTicket
    /// </summary>
    public int NumeroTicket { get; set; }

    /// <summary>
    /// Fecha Pesaje
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaPesaje { get; set; }

    /// <summary>
    /// Chofer ID
    /// </summary>
    public int IdChofer { get; set; }

    /// <summary>
    /// Vehículo ID
    /// </summary>
    public int IdVehiculo { get; set; }

    /// <summary>
    /// Transportista ID
    /// </summary>
    public int? IdTransportista { get; set; }

    /// <summary>
    /// Tipo Movto ID
    /// </summary>
    public int? IdTipoMovimiento { get; set; }

    /// <summary>
    /// Almacén Origen ID
    /// </summary>
    public int? IdAlmacenOrigen { get; set; }

    /// <summary>
    /// Almacén Destino ID
    /// </summary>
    public int? IdAlmacenDestino { get; set; }

    /// <summary>
    /// Serie Guía Remisión
    /// </summary>
    [Required]
    [StringLength(10)]
    public string GuiaRemisionSerie { get; set; }

    /// <summary>
    /// Nro Guía Remisión
    /// </summary>
    [Required]
    [StringLength(10)]
    public string GuiaRemisionNumero { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [ForeignKey("IdTipoMovimiento")]
    [InverseProperty("Ticket")]
    public virtual TipoMovimiento IdTipoMovimientoNavigation { get; set; }

    [InverseProperty("IdTicketNavigation")]
    public virtual ICollection<TicketLog> TicketLog { get; set; } = new List<TicketLog>();

    [InverseProperty("IdTicketNavigation")]
    public virtual ICollection<TicketPesajes> TicketPesajes { get; set; } = new List<TicketPesajes>();
}