// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class TicketLog
{
    /// <summary>
    /// Ticket Log ID
    /// </summary>
    [Key]
    public int IdTicketLog { get; set; }

    /// <summary>
    /// Ticket ID
    /// </summary>
    public int IdTicket { get; set; }

    /// <summary>
    /// Motivo del Log
    /// </summary>
    [Required]
    [StringLength(100)]
    public string MotivoCrud { get; set; }

    /// <summary>
    /// Decía
    /// </summary>
    [Required]
    [StringLength(100)]
    public string DatoDecia { get; set; }

    /// <summary>
    /// Dice
    /// </summary>
    [Required]
    [StringLength(100)]
    public string DatoDice { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [ForeignKey("IdTicket")]
    [InverseProperty("TicketLog")]
    public virtual Ticket IdTicketNavigation { get; set; }
}