// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Jodami.Entity;

public partial class TipoDireccion
{
    /// <summary>
    /// Tipo Direccón ID
    /// </summary>
    [Key]
    public int IdTipoDireccion { get; set; }

    /// <summary>
    /// Descripción
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Descripcion { get; set; }
 
    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [InverseProperty("IdTipoDireccionNavigation")]
    public virtual ICollection<Direccion_> Direccion_ { get; set; } = new List<Direccion_>();
}