// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Jodami.Entity;

public partial class TipoDocumentoIdentidad
{
    /// <summary>
    /// Tipo Dcmto ID
    /// </summary>
    [Key]
    public int IdTipoDcmtoIdentidad { get; set; }

    /// <summary>
    /// Descripción
    /// </summary>
    [Required]
    [StringLength(60)]
    public string Descripcion { get; set; }

    /// <summary>
    /// Símbolo
    /// </summary>
    [Required]
    [StringLength(20)]
    public string Simbolo { get; set; }

    /// <summary>
    /// Código SUNAT
    /// </summary>
    [Required]
    [StringLength(20)]
    public string IdCodigoSunat { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [InverseProperty("IdTipoDcmtoNavigation")]
    public virtual ICollection<Choferes> Choferes { get; set; } = new List<Choferes>();

    [InverseProperty("IdTipoDcmtoIdentidadNavigation")]
    public virtual ICollection<Socio> Socio { get; set; } = new List<Socio>();
}