// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jodami.Entity;

public partial class UnidadMedida
{
    /// <summary>
    /// Unidad ID
    /// </summary>
    [Key]
    public int IdUnidad { get; set; }

    /// <summary>
    /// Descripción
    /// </summary>
    [Required]
    [StringLength(60)]
    public string Descripcion { get; set; }

    /// <summary>
    /// Símbolo
    /// </summary>
    [Required]
    [StringLength(20)]
    public string Simbolo { get; set; }

    /// <summary>
    /// Código SUNAT
    /// </summary>
    [Required]
    [StringLength(20)]
    public string IdSunat { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Usuario
    /// </summary>
    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime FechaRegistro { get; set; }

    [InverseProperty("IdUnidadCompraNavigation")]
    public virtual ICollection<Articulo> ArticuloIdUnidadCompraNavigation { get; set; } = new List<Articulo>();

    [InverseProperty("IdUnidadInventarioNavigation")]
    public virtual ICollection<Articulo> ArticuloIdUnidadInventarioNavigation { get; set; } = new List<Articulo>();

    [InverseProperty("IdUnidadVentaNavigation")]
    public virtual ICollection<Articulo> ArticuloIdUnidadVentaNavigation { get; set; } = new List<Articulo>();
}