// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Jodami.Entity;

public partial class Usuario
{
    /// <summary>
    /// Usuario ID
    /// </summary>
    [Key]
    public int IdUsuario { get; set; }

    /// <summary>
    /// Nombre
    /// </summary>
    [StringLength(60)]
    public string Nombre { get; set; }

    /// <summary>
    /// Correo
    /// </summary>
    [StringLength(100)]
    public string Correo { get; set; }

    /// <summary>
    /// Celular
    /// </summary>
    [StringLength(50)]
    public string Telefono { get; set; }

    /// <summary>
    /// Rol ID
    /// </summary>
    public int? IdRol { get; set; }

    /// <summary>
    /// Url Foto
    /// </summary>
    [StringLength(500)]
    public string UrlFoto { get; set; }

    /// <summary>
    /// Nombre Foto
    /// </summary>
    [StringLength(100)]
    public string NombreFoto { get; set; }

    /// <summary>
    /// Clave
    /// </summary>
    [StringLength(100)]
    public string Clave { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool? EsActivo { get; set; }
 
    /// <summary>
    /// Auditoría Fecha
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? FechaRegistro { get; set; }

    [Required]
    [StringLength(60)]
    public string UsuarioName { get; set; }

    [ForeignKey("IdRol")]
    [InverseProperty("Usuario")]
    public virtual Rol IdRolNavigation { get; set; }
}